---
- name: Change hostname using curly braces
  hosts: pynet-sf-srx
  tasks:
          - name: Verifying NETCONF
            wait_for: host={{ ansible_ssh_host }} port=830

          - name: Change Hostname
            junos_install_config: host={{ ansible_ssh_host }} user={{ juniper_user }} passwd={{ juniper_passwd }} ex2.conf overwrite=false

