---
#Use the napalm_get_facts Ansible module and one of the Arista switches to view the data you get back from the ‘facts’, ‘interfaces’, and ‘bgp_neighbors’ filters.
- name: Arista interfaces and bgp neighbors
  hosts: pynet-sw2
  tasks:
    - name: Get info
      napalm_get_facts:
        hostname: "{{ eapi_hostname }}"
        username: "{{ eapi_username }}"
        password: "{{ eapi_password }}"
        dev_os: eos
        filter: [facts, interfaces, bgp_neighbors]
      register: result

    - name: Debugging
      debug: var=result

