--- 

- name: Configure primary Ethernet Interface as Trunk
  hosts: arista

  tasks:
    - name: Set Ethernet3 to trunk mode, Vlan 1
      eos_switchport: name=Ethernet3 mode=trunk 
          trunk_allowed_vlans=701,710,711 
          trunk_native_vlan=1 access_vlan=1
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          transport=https

