--- 

- name: Restore Settings
  hosts: arista

  tasks:
    - name: Restore Ethernet3 switchport settings
      eos_switchport: name=Ethernet3 mode=access
          trunk_allowed_vlans=1-4094
          access_vlan=1
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          transport=https

    - name: Restore Ethernet3 Interface Description
      eos_interface: name=Ethernet3 
          description=
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          transport=https

    - name: Remove VLANs
      eos_vlan: name={{item.name}} vlanid={{item.vlanid}} state=absent
          username={{ eapi_username }}
          password={{ eapi_password }}
          host={{ eapi_hostname }}
          transport=https
      with_items:
          - {name: BLUE, vlanid: 701}
          - {name: RED, vlanid: 710}
          - {name: GREEN, vlanid: 711}
